name: codable_forked
description: A serialization library for converting dynamic, structured data (JSON, YAML) into Dart types. Forked for null safety and some minor fixes.
version: 1.0.0+3
#homepage: https://github.com/stablekernel/dart-codable
homepage: https://github.com/hpoul/dart-codable
#author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ">=1.3.0 <2.0.0"

dev_dependencies:
  test: ">=1.16.4 <2.0.0"
